### ISSUE TITLE
Timeout shows red instead of yellow error

### ISSUE THREAD

**Issue by hpwaldegger** [SCS-CBU-CED-IAM/mobileid-helper#78] opened 2016-08-18 13:35 UTC
Timeout (sending a request and waiting until the error is displayed) shows red error (infrastructure error) instead of 'yello error' (user error). This is probably triggered by a system timeout before the system retuns 208, as the test number (+41000092208) shows the correct behavoir.

**Comment by hpwaldegger** [comment] 2016-08-25 13:12
Solution concept: Set the "red dot" as default and change to "green dot" after the signature request finished successful.

**Comment by phaupt** [comment] 2017-03-14 08:08
I agree that the a timeout waiting for the user should result in a yellow warning rather than a red error.
However the problem is related to the "connection_timeout"-parameter of 90s that has actually no effect. So the default socket timeout of 60s was hitting instead and lead to the red error. This will be fixed in the next commit.

**Closed** 2017-03-14 08:18 UTC
Labels: bug
